import type { StageSample } from '@pen/contracts';
import { FakeLanguageModel } from '@pen/llm';
import type { Onten } from '@pen/onten';
import { SilentSynthesizer } from '@pen/voice';
import { describe, expect, it } from 'vitest';
import type { LessonMemo } from '../src/lesson-memo.js';
import { SessionMetrics } from '../src/metrics.js';
import { SessionRoom } from '../src/room.js';
import {
  CANONICAL_ID,
  expert,
  MemoryTransport,
  planCompletion,
  preparedPack,
  segmentScript,
  until,
} from './fixtures.js';

/** The fake model, presented as luna so "what a reuse saved" is priced (its own calls still cost $0). */
function model() {
  const fake = new FakeLanguageModel(
    [segmentScript(1, 2), segmentScript(2, 2), segmentScript(3, 2)],
    [planCompletion(3), { purpose: 'recap', value: { points: ['one'] } }],
  );
  return {
    id: 'openai:gpt-5.6-luna',
    streamEvents: (r: Parameters<typeof fake.streamEvents>[0]) => fake.streamEvents(r),
    complete: <T>(r: Parameters<typeof fake.complete<T>>[0]) => fake.complete(r),
  };
}

async function session(
  onten: Onten,
  memo: LessonMemo,
  id: string,
  opts: { expertId?: string } = {},
) {
  const transport = new MemoryTransport();
  const samples: StageSample[] = [];
  const metrics = new SessionMetrics({
    sessionId: id,
    startedAt: Date.now(),
    onSample: (s) => samples.push(s),
  });
  const room = new SessionRoom({
    sessionId: id,
    topic: 'How Transformers work in LLMs',
    host: { id: 'host-1234', name: 'Sam', plan: 'free' },
    expert: opts.expertId ? { ...expert, id: opts.expertId } : expert,
    band: 'beginner',
    language: 'en',
    locale: 'en-US',
    onten,
    runtime: onten.newRuntime(),
    memo,
    model: model(),
    synthesizer: new SilentSynthesizer(),
    voice: 'v',
    sampleRate: 44100,
    transport,
    acquirer: null,
    targetMinutes: 3,
    metrics,
  });
  await room.start();
  return { room, transport, samples, metrics };
}

const llm = (samples: StageSample[], purpose: string) =>
  samples.filter((s) => s.stage === 'llm' && s.meta.purpose === purpose);

describe('lesson reuse across sessions (zero redundant generation)', () => {
  it('a session that ends after one segment memoises it; the next session reuses the plan and that segment and generates only the rest', async () => {
    const { onten, memo } = await preparedPack();

    // Session 1: generates the plan and segment 0, then ends early (before the host hears segment 1).
    const a = await session(onten, memo, 'sess-a');
    await until(() => a.transport.audio.some((h) => h.sayId === 'L0.s2' && h.final));
    await a.room.end();
    expect(llm(a.samples, 'plan')).toHaveLength(1);
    expect(llm(a.samples, 'plan')[0]?.meta.reused).toBe(false);
    expect(llm(a.samples, 'lesson').map((s) => s.meta.reused)).toEqual([false]);
    const stored = await memo.find(CANONICAL_ID, 'beginner', expert.id);
    expect(stored?.cuesBySegment.map((c) => c.length)).toEqual([2, 0, 0]);
    expect(stored?.costUsd.segments).toHaveLength(3);

    // Session 2: same topic, band and persona → the pack is a hit, the plan and segment 0 come from the memo.
    const b = await session(onten, memo, 'sess-b');
    await until(() => b.transport.audio.some((h) => h.sayId === 'L0.s2' && h.final));
    expect(b.room.getState().plan?.segments).toHaveLength(3);
    const resolve = b.samples.find((s) => s.stage === 'resolve');
    expect(resolve?.meta).toMatchObject({ canonicalId: CANONICAL_ID, reused: true });
    expect(resolve?.meta.savedUsd).toBeGreaterThan(0);
    expect(llm(b.samples, 'plan')[0]?.meta).toMatchObject({ reused: true, memo: true });
    expect(llm(b.samples, 'lesson')[0]?.meta).toMatchObject({
      reused: true,
      memo: true,
      segment: 0,
    });
    expect(typeof llm(b.samples, 'lesson')[0]?.meta.savedUsd).toBe('number');
    // Segment 0 was not generated by the model this time: no fresh lesson call for it.
    expect(llm(b.samples, 'lesson').filter((s) => !s.meta.reused)).toHaveLength(0);
    // The host hears on → segment 1 is generated (the memo had nothing for it) and memoised.
    b.room.handle('host-1234', { kind: 'progress', seq: 0, clockMs: 1000 });
    await until(() => b.transport.cues().some((c) => c.segment === 1));
    await until(() =>
      llm(b.samples, 'lesson').some((s) => s.meta.segment === undefined && !s.meta.reused),
    );
    await b.room.end();
    const grown = await memo.find(CANONICAL_ID, 'beginner', expert.id);
    expect(grown?.id).toBe(stored?.id);
    expect(grown?.cuesBySegment.map((c) => c.length)).toEqual([2, 2, 0]);
    expect(grown?.timesReused).toBe(1);

    // Session 3 with another persona: nothing of Ada's script is served.
    const c = await session(onten, memo, 'sess-c', { expertId: 'juno-park' });
    expect(llm(c.samples, 'plan')[0]?.meta.reused).toBe(false);
    await c.room.end();
  }, 20_000);
});
