packages:
  - apps/*
  - services/*
  - packages/*
allowBuilds:
  esbuild: true
  '@biomejs/biome': true
  '@electric-sql/pglite': true
  electron: true
  '@sentry/cli': true
  '@tailwindcss/oxide': true
