/**
 * The mark, against the artwork it came from.
 *
 * `src/components/PenLogo.tsx`, `apps/web/public/favicon.svg` and the admin's
 * copy are generated by `scripts/mark.ts` from `brand/*.svg`, which is the
 * owner's drawing exactly as it arrived. Generated-and-checked-in is only
 * trustworthy if something re-derives it, so this file does: it regenerates
 * every artefact and fails if what is on disk has drifted.
 *
 * It also holds the facts a regeneration cannot catch, because they are the
 * point of the exercise rather than a product of it:
 *
 *   · no literal hex survives into the component — the ink is
 *     `--color-mark-ink` and the triangle is `primary-fixed`, so one component
 *     carries the owner's two drawings and the red is not written down a
 *     fourth time;
 *   · the dark artwork is the light artwork with white ink and nothing else,
 *     which is the assumption that makes a single token sufficient. The day
 *     that stops being true, this fails and the product needs two components.
 */
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  ACCENT_TOKEN,
  ARTWORK,
  art,
  BBOX,
  BRAND_RED,
  component,
  FAVICON_SIDE,
  faviconSvg,
  INK,
  INK_TOKEN,
  isInked,
  LOCKUP_GAP,
  MARK_ACCENT,
  paths,
  WHITE,
} from '../scripts/mark.js';

const DESIGN = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const REPO = resolve(DESIGN, '../..');
const read = (rel: string): string =>
  readFileSync(rel.startsWith('apps/') ? join(REPO, rel) : join(DESIGN, rel), 'utf8');

const GENERATED = [
  'src/components/PenLogo.tsx',
  'apps/web/public/favicon.svg',
  'apps/admin/public/favicon.svg',
] as const;

/**
 * The attributes of each `<path>` the component ships, and nothing else. The
 * header comment discusses the same attribute names it sets, so a check that
 * greps the whole file can be satisfied by the prose alone.
 */
const componentPaths = (): string[] =>
  [...read('src/components/PenLogo.tsx').matchAll(/<path\n([\s\S]*?)\/>/g)].map((m) => m[1] ?? '');

describe('the generated artefacts are still the artwork', () => {
  it.each(GENERATED)('%s is what the generator writes today', (file) => {
    const expected = file.endsWith('.tsx') ? component() : faviconSvg();
    expect(read(file)).toBe(expected);
  });

  /**
   * The owner supplies four files: the mark and the lockup, each twice. The
   * dark pair may repaint the ink and nothing else — if one of them is ever
   * redrawn on its own, a single token cannot express the difference and the
   * product needs two components instead. `art()` enforces it; this says so
   * out loud, and names the files so a fifth one is not added silently.
   */
  it('the artwork is four files, and every one is the drawing BBOX was measured against', () => {
    expect(Object.keys(ARTWORK).sort()).toEqual([
      'pen-favicon-dark.svg',
      'pen-favicon.svg',
      'pen-logo-dark.svg',
      'pen-logo.svg',
    ]);
    // art() throws on a checksum or ink mismatch; reaching here is the pass.
    expect(() => art()).not.toThrow();
  });

  it('the dark artwork is the light artwork with white ink and nothing else', () => {
    for (const [light, dark, id] of [
      ['brand/pen-favicon.svg', 'brand/pen-favicon-dark.svg', 'icon'],
      ['brand/pen-logo.svg', 'brand/pen-logo-dark.svg', 'wordmark'],
      ['brand/pen-logo.svg', 'brand/pen-logo-dark.svg', 'icon'],
    ] as const) {
      const [a, b] = [paths(read(light), id), paths(read(dark), id)];
      // Geometry, and the stroke's shape with it: a cap or a width that moved
      // between the two files is a redrawn mark, not a repainted one.
      const shape = (p: (typeof a)[number]) => [
        p.d,
        p.transform,
        p.strokeWidth,
        p.strokeLinecap,
        p.strokeLinejoin,
      ];
      expect(b.map(shape)).toEqual(a.map(shape));

      // Both painted properties. The diagonals have no fill at all, so a
      // fill-only comparison would see `none` on each side and pass however
      // the strokes were coloured.
      const repaint = (v: string | undefined) =>
        v === undefined ? undefined : v.toUpperCase() === INK ? WHITE : v.toUpperCase();
      expect(b.map((p) => [p.fill.toUpperCase(), p.stroke?.toUpperCase()])).toEqual(
        a.map((p) => [repaint(p.fill), repaint(p.stroke)]),
      );
    }
  });

  it('the two supplied files draw the same icon', () => {
    const favicon = paths(read('brand/pen-favicon.svg'), 'icon');
    const logo = paths(read('brand/pen-logo.svg'), 'icon');
    expect(logo).toEqual(favicon);
  });

  /**
   * The strongest claim this suite makes: every path in the shipped component
   * is a path in the artwork, character for character. A generator that
   * "tidied" a coordinate would be a redrawn logo, and it would pass a
   * screenshot review.
   */
  it('the diagonals are still strokes, and the component carries what paints them', () => {
    // The drawing stopped being all-fills: the two diagonals are open curves
    // whose width, cap and `fill="none"` are the difference between this mark
    // and a different one. Copying `d` alone would render two hairlines.
    const { icon } = art();
    const strokes = icon.filter((p) => p.stroke !== undefined && p.stroke !== 'none');
    expect(strokes).toHaveLength(2);
    for (const p of strokes) {
      expect(p.fill).toBe('none');
      expect(p.strokeWidth).toBe('43');
      expect(p.strokeLinecap).toBe('round');
    }
    // Counted over the <path> elements alone. Matching the whole file would
    // also count the header comment, which quotes `fill="none"` while
    // explaining it — prose passing a test is exactly what this suite is for.
    const drawn = componentPaths();
    const carrying = (attr: string) => drawn.filter((a) => a.includes(attr)).length;
    // Twice each: PenMark draws the icon, and the lockup draws it again.
    expect(carrying('strokeWidth="43"')).toBe(4);
    expect(carrying('strokeLinecap="round"')).toBe(4);
    expect(carrying('fill="none"')).toBe(4);
    // Every diagonal takes the ink as a token, never a literal.
    expect(
      drawn
        .filter((a) => a.includes('strokeWidth="43"'))
        .every((a) => a.includes('stroke="var(--color-mark-ink)"')),
    ).toBe(true);
    // Seven inked strokes in all: four diagonals, and the three wordmark
    // glyphs, which this drawing also strokes — at 3, to weight the letters.
    expect(carrying('stroke="var(--color-mark-ink)"')).toBe(7);
    expect(carrying('strokeWidth="3"')).toBe(3);
  });

  it('every path in the component is copied out of the artwork verbatim', () => {
    const { icon, wordmark } = art();
    const drawn = [...wordmark, ...icon].map((p) => p.d);
    const shipped = [...read('src/components/PenLogo.tsx').matchAll(/\bd="([^"]*)"/g)].map(
      (m) => m[1],
    );
    // The icon appears twice in the component: alone in PenMark, and again in
    // the lockup. Both copies have to be the artwork.
    expect(shipped).toHaveLength(icon.length + drawn.length);
    for (const d of shipped) expect(drawn).toContain(d);
    for (const d of drawn) expect(shipped).toContain(d);
  });
});

/** What the component actually paints with — prose in the header does not count. */
const fills = (): string[] =>
  [...read('src/components/PenLogo.tsx').matchAll(/\bfill="([^"]*)"/g)].map((m) => m[1] ?? '');

/** The other painted property. The diagonals are stroke-only, so this is the mark. */
const strokes = (): string[] =>
  [...read('src/components/PenLogo.tsx').matchAll(/\sstroke="([^"]*)"/g)].map((m) => m[1] ?? '');

describe('the two substitutions, which are the reason for the pipeline', () => {
  it('nothing in the component is painted a literal hex', () => {
    // #000000 is 1.27:1 on `surface-container` in dark, so a literal one is a
    // logo half the product cannot see; the brand is 2.7:1 there. Both hexes
    // are named in the header comment on purpose — this is about what gets
    // painted.
    for (const paint of [...fills(), ...strokes()]) expect(paint).not.toMatch(/^#/);
  });

  it('the ink became the token, on every property that carried it', () => {
    const { icon, wordmark } = art();
    // The icon is drawn twice: alone in PenMark, again inside the lockup.
    const all = [...wordmark, ...icon, ...icon];
    const inkedFills = all.filter((p) => p.fill.toUpperCase() === INK).length;
    const inkedStrokes = all.filter((p) => p.stroke?.toUpperCase() === INK).length;
    // The wordmark is filled and stroked in the ink; the diagonals are only
    // stroked. Both counts have to be non-zero or the check is vacuous.
    expect(inkedFills).toBeGreaterThan(0);
    expect(inkedStrokes).toBeGreaterThan(0);
    expect(fills().filter((f) => f === INK_TOKEN)).toHaveLength(inkedFills);
    expect(strokes().filter((f) => f === INK_TOKEN)).toHaveLength(inkedStrokes);
    expect(all.filter((p) => isInked(p))).toHaveLength(inkedFills + inkedStrokes - 3);
  });

  it('the ink is a token and not currentColor, which would be #e2e2e2 in dark', () => {
    // The owner's dark drawing is pure white. Inheriting `on-surface` would
    // put the mark at #e2e2e2 — close enough to look deliberate and wrong.
    expect(fills()).not.toContain('currentColor');
    expect(strokes()).not.toContain('currentColor');
    expect(INK_TOKEN).toBe('var(--color-mark-ink)');
  });

  it('tokens.css carries the mark ink in both themes, and they are the artwork', () => {
    const tokens = read('src/styles/tokens.css');
    const declared = [...tokens.matchAll(/--color-mark-ink:\s*(#[0-9a-f]{6})/gi)].map((m) =>
      (m[1] ?? '').toUpperCase(),
    );
    // @theme, the prefers-color-scheme block, and [data-theme="dark"].
    expect(declared).toEqual([INK, WHITE, WHITE]);
  });

  it('the delta is named, and appears once in the mark and once in the lockup', () => {
    expect(ACCENT_TOKEN).toBe('var(--color-mark-accent)');
    expect(fills().filter((f) => f === ACCENT_TOKEN)).toHaveLength(2);
    expect(fills()).not.toContain('var(--color-primary-fixed)');
  });

  it('tokens.css carries the delta in both themes, and they are the palette', () => {
    const tokens = read('src/styles/tokens.css');
    const declared = [...tokens.matchAll(/--color-mark-accent:\s*(#[0-9a-f]{6})/gi)].map((m) =>
      (m[1] ?? '').toUpperCase(),
    );
    // @theme only: the delta is the brand on both grounds (the owner's
    // ruling), so the dark blocks never redeclare it.
    expect(declared).toEqual([MARK_ACCENT]);
    // The artwork's red is recognised and never painted: no theme block declares it.
    // (The candidate families below `[data-brand=` still name it, as the seed they record.)
    expect(tokens.slice(0, tokens.indexOf(':root[data-brand=')).toUpperCase()).not.toContain(
      BRAND_RED,
    );
  });

  it('the favicon carries its own dark rule, since it has no document to inherit from', () => {
    const svg = faviconSvg();
    expect(svg).toContain('@media (prefers-color-scheme: dark)');
    // The delta is the brand on both strips and sits outside the media query; the
    // artwork's red is nowhere in the file.
    expect(svg).not.toMatch(new RegExp(BRAND_RED, 'i'));
    expect(svg.match(new RegExp(`\\.delta-fill \\{ fill: ${MARK_ACCENT} \\}`, 'g'))).toHaveLength(
      1,
    );
    expect(svg.match(/class="delta-fill"/g)).toHaveLength(1);
    expect(svg).not.toMatch(/\.brand\s*\{/);
  });

  /**
   * The favicon themes the diagonals by class, and the class may only touch
   * the property the artwork painted. A `.ink { fill: … }` rule — which is
   * what this file used to emit — would fill the area between each curve and
   * its chord, putting a black wedge through the mark on every tab.
   */
  it('the favicon themes the stroke, and never fills a stroke-only path', () => {
    const svg = faviconSvg();
    expect(svg).toContain('.ink-stroke { stroke:');
    expect(svg).not.toMatch(/\.ink-stroke\s*\{\s*fill:/);
    expect(svg).not.toMatch(/\.ink-fill\s*\{/);
    // Each diagonal keeps its own width and cap, and is explicitly unfilled.
    expect(svg.match(/stroke-width="43"/g)).toHaveLength(2);
    expect(svg.match(/stroke-linecap="round"/g)).toHaveLength(2);
    expect(svg.match(/fill="none"/g)).toHaveLength(2);
  });
});

describe('the crop', () => {
  /**
   * The supplied files are padded and carry a large inherited translate, so a
   * `size` on the component would have meant "this many pixels of box, some of
   * it empty" — and the mark would have sat visibly small beside the text it
   * is aligned to. Both artefacts are re-cropped to the artwork's own bounding
   * box. These numbers were measured with `getBBox()` in Chromium; the test
   * that re-measures them lives in the web app's Playwright suite, because
   * that is where a browser is.
   */
  it('the component is cropped to the artwork, with nothing left over', () => {
    const file = read('src/components/PenLogo.tsx');
    expect(file).toContain(`viewBox="0 0 ${BBOX.icon.w} ${BBOX.icon.h}"`);
    // The lockup's box is the artwork's plus the gap the owner asked for between the word and the icon.
    expect(file).toContain(
      `viewBox="0 0 ${Math.round((BBOX.logo.w + LOCKUP_GAP) * 1000) / 1000} ${BBOX.logo.h}"`,
    );
    expect(file).toContain(`<g transform="translate(${LOCKUP_GAP} 0)">`);
    expect(LOCKUP_GAP).toBeGreaterThan(0);
    expect(file).toContain(`translate(${-BBOX.icon.x} ${-BBOX.icon.y})`);
    expect(file).toContain(`translate(${-BBOX.logo.x} ${-BBOX.logo.y})`);
  });

  /**
   * The crop has to clear the paint, not the centre line. `getBBox()` reports
   * the icon starting at x=1090, which is where the first diagonal's round cap
   * begins — the ink reaches 21.5 further, and a box measured the naive way
   * shaves the cap off both strokes at every size. These numbers come from
   * `measure-bbox.mjs`, which grows each path's box by half its stroke width.
   */
  it('the box clears the stroke, not just the geometry', () => {
    const { icon } = art();
    const half = Math.max(
      ...icon.map((p) => (p.stroke && p.stroke !== 'none' ? Number(p.strokeWidth) / 2 : 0)),
    );
    expect(half).toBe(21.5);
    // The leftmost diagonal starts at x=1090 in the artwork's own units.
    expect(BBOX.icon.x).toBeCloseTo(1090 - half, 3);
    // And the square the favicon crops to has to be at least as tall as that.
    expect(FAVICON_SIDE).toBeGreaterThanOrEqual(BBOX.icon.h);
  });

  it('the favicon is square and the icon is centred in it', () => {
    const svg = faviconSvg();
    expect(svg).toContain(`viewBox="0 0 ${FAVICON_SIDE} ${FAVICON_SIDE}"`);
    const found = /translate\((-?[\d.]+) (-?[\d.]+)\)/.exec(svg);
    const [dx, dy] = [Number(found?.[1]), Number(found?.[2])];
    expect(dx + BBOX.icon.x + BBOX.icon.w / 2).toBeCloseTo(FAVICON_SIDE / 2, 3);
    expect(dy + BBOX.icon.y + BBOX.icon.h / 2).toBeCloseTo(FAVICON_SIDE / 2, 3);
  });

  it('the icon keeps the artwork aspect, so neither axis can be squashed', () => {
    // PenMark and PenLogo both take a height and derive the width. If that
    // arithmetic were ever inverted the mark would still render, just wrong.
    const file = read('src/components/PenLogo.tsx');
    expect(file).toContain('width={(size * ICON.w) / ICON.h}');
    expect(file).toContain('width={(size * LOGO.w) / LOGO.h}');
  });
});
