/**
 * The mark, against the artwork it came from.
 *
 * `src/components/PenLogo.tsx`, `apps/web/public/favicon.svg` and the admin's
 * copy are generated by `scripts/mark.ts` from `brand/*.svg`, which is the
 * owner's drawing exactly as it arrived. Generated-and-checked-in is only
 * trustworthy if something re-derives it, so this file does: it regenerates
 * every artefact and fails if what is on disk has drifted.
 *
 * It also holds the two facts a regeneration cannot catch, because they are
 * the point of the exercise rather than a product of it: that no charcoal
 * survives into the component (the artwork's single #2A2A2A is invisible in
 * dark, which is the whole reason this pipeline exists), and that the red is
 * named as `primary-fixed` rather than written out a fourth time.
 */
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  art,
  BBOX,
  BRAND_RED,
  CHARCOAL,
  component,
  FAVICON_SIDE,
  faviconSvg,
  paths,
} from '../scripts/mark.js';

const DESIGN = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const REPO = resolve(DESIGN, '../..');
const read = (rel: string): string =>
  readFileSync(rel.startsWith('apps/') ? join(REPO, rel) : join(DESIGN, rel), 'utf8');

const GENERATED = [
  'src/components/PenLogo.tsx',
  'apps/web/public/favicon.svg',
  'apps/admin/public/favicon.svg',
] as const;

describe('the generated artefacts are still the artwork', () => {
  it.each(GENERATED)('%s is what the generator writes today', (file) => {
    const expected = file.endsWith('.tsx') ? component() : faviconSvg();
    expect(read(file)).toBe(expected);
  });

  it('the two supplied files draw the same icon', () => {
    const favicon = paths(read('brand/pen-favicon.svg'), 'icon');
    const logo = paths(read('brand/pen-logo.svg'), 'icon');
    expect(logo).toEqual(favicon);
  });

  /**
   * The strongest claim this suite makes: every path in the shipped component
   * is a path in the artwork, character for character. A generator that
   * "tidied" a coordinate would be a redrawn logo, and it would pass a
   * screenshot review.
   */
  it('every path in the component is copied out of the artwork verbatim', () => {
    const { icon, wordmark } = art();
    const drawn = [...wordmark, ...icon].map((p) => p.d);
    const shipped = [...read('src/components/PenLogo.tsx').matchAll(/\bd="([^"]*)"/g)].map(
      (m) => m[1],
    );
    // The icon appears twice in the component: alone in PenMark, and again in
    // the lockup. Both copies have to be the artwork.
    expect(shipped).toHaveLength(icon.length + drawn.length);
    for (const d of shipped) expect(drawn).toContain(d);
    for (const d of drawn) expect(shipped).toContain(d);
  });
});

/** What the component actually paints with — prose in the header does not count. */
const fills = (): string[] =>
  [...read('src/components/PenLogo.tsx').matchAll(/\bfill="([^"]*)"/g)].map((m) => m[1] ?? '');

describe('the two substitutions, which are the reason for the pipeline', () => {
  it('nothing in the component is painted a literal hex', () => {
    // #2A2A2A is 1.07:1 on `surface-container` in dark, so a literal one is a
    // logo half the product cannot see; #E62117 is right but would be a fourth
    // place the brand is written down. Both hexes are named in the header
    // comment on purpose — this is about what gets painted.
    for (const fill of fills()) expect(fill).not.toMatch(/^#/);
  });

  it('the charcoal became currentColor, once per path that had it', () => {
    const { icon, wordmark } = art();
    const charcoals = [...wordmark, ...icon, ...icon].filter(
      (p) => p.fill.toUpperCase() === CHARCOAL,
    ).length;
    expect(fills().filter((f) => f === 'currentColor')).toHaveLength(charcoals);
  });

  it('the red is named, and appears once in the mark and once in the lockup', () => {
    expect(fills().filter((f) => f === 'var(--color-primary-fixed)')).toHaveLength(2);
  });

  it('primary-fixed is the hex the artwork used, so naming it changed nothing', () => {
    const tokens = read('src/styles/tokens.css');
    const found = /--color-primary-fixed:\s*(#[0-9a-f]{6})/i.exec(tokens);
    expect(found?.[1]?.toUpperCase()).toBe(BRAND_RED);
  });

  it('the favicon carries its own dark rule, since it has no document to inherit from', () => {
    const svg = faviconSvg();
    expect(svg).toContain('@media (prefers-color-scheme: dark)');
    // The triangle is deliberately outside it: it is the one part of the mark
    // that reads on both grounds, and the part that stays the brand when a
    // client ignores the media query altogether.
    expect(svg).toMatch(new RegExp(`fill="${BRAND_RED}"`, 'i'));
    expect(svg).not.toMatch(/\.brand\s*\{/);
  });
});

describe('the crop', () => {
  /**
   * The supplied files are padded and carry a large inherited translate, so a
   * `size` on the component would have meant "this many pixels of box, some of
   * it empty" — and the mark would have sat visibly small beside the text it
   * is aligned to. Both artefacts are re-cropped to the artwork's own bounding
   * box. These numbers were measured with `getBBox()` in Chromium; the test
   * that re-measures them lives in the web app's Playwright suite, because
   * that is where a browser is.
   */
  it('the component is cropped to the artwork, with nothing left over', () => {
    const file = read('src/components/PenLogo.tsx');
    expect(file).toContain(`viewBox="0 0 ${BBOX.icon.w} ${BBOX.icon.h}"`);
    expect(file).toContain(`viewBox="0 0 ${BBOX.logo.w} ${BBOX.logo.h}"`);
    expect(file).toContain(`translate(${-BBOX.icon.x} ${-BBOX.icon.y})`);
    expect(file).toContain(`translate(${-BBOX.logo.x} ${-BBOX.logo.y})`);
  });

  it('the favicon is square and the icon is centred in it', () => {
    const svg = faviconSvg();
    expect(svg).toContain(`viewBox="0 0 ${FAVICON_SIDE} ${FAVICON_SIDE}"`);
    const found = /translate\((-?[\d.]+) (-?[\d.]+)\)/.exec(svg);
    const [dx, dy] = [Number(found?.[1]), Number(found?.[2])];
    expect(dx + BBOX.icon.x + BBOX.icon.w / 2).toBeCloseTo(FAVICON_SIDE / 2, 3);
    expect(dy + BBOX.icon.y + BBOX.icon.h / 2).toBeCloseTo(FAVICON_SIDE / 2, 3);
  });

  it('the icon keeps the artwork aspect, so neither axis can be squashed', () => {
    // PenMark and PenLogo both take a height and derive the width. If that
    // arithmetic were ever inverted the mark would still render, just wrong.
    const file = read('src/components/PenLogo.tsx');
    expect(file).toContain('width={(size * ICON.w) / ICON.h}');
    expect(file).toContain('width={(size * LOGO.w) / LOGO.h}');
  });
});
