import { getStroke } from 'perfect-freehand';
import { useMemo } from 'react';
import { SVGContainer, T, type TLBaseShape } from 'tldraw';
import { outlineToPath, revealStrokes, type Stroke } from '../primitives.js';
import { EMPHASIS_VALUES, inkVar, PaperShapeUtil, resolveInk } from './paper-shape.js';
import { type InkStrokeProps, SHAPE_TYPE, STROKE_STYLE } from './props.js';

/**
 * `ink-stroke`: a progressive freehand stroke (boxes, circles, arrows,
 * underlines, highlight rings, code frames). Points are generated by the
 * primitives module and revealed by arc length; perfect-freehand turns the
 * visible prefix into a pressure-shaped outline each frame. See README for
 * why this is a custom shape rather than tldraw's native `draw`.
 */
export type InkStrokeShape = TLBaseShape<'ink-stroke', InkStrokeProps>;

export class InkStrokeShapeUtil extends PaperShapeUtil<InkStrokeShape> {
  static override type = SHAPE_TYPE.inkStroke;
  static override props = {
    strokes: T.arrayOf(T.arrayOf(T.arrayOf(T.number))),
    w: T.number,
    h: T.number,
    progress: T.number,
    emphasis: T.literalEnum(...EMPHASIS_VALUES),
    size: T.number,
    role: T.literalEnum('sketch', 'highlight', 'frame', 'arrow', 'underline'),
  };

  getDefaultProps(): InkStrokeProps {
    return {
      strokes: [],
      w: 1,
      h: 1,
      progress: 1,
      emphasis: 'ink',
      size: STROKE_STYLE.size,
      role: 'sketch',
    };
  }

  component(shape: InkStrokeShape) {
    return <InkStrokeView shape={shape} />;
  }

  override toSvg(shape: InkStrokeShape) {
    const color = resolveInk(this.editor.getContainer(), shape.props.emphasis);
    return <StrokePaths props={{ ...shape.props, progress: 1 }} color={color} />;
  }
}

function InkStrokeView({ shape }: { shape: InkStrokeShape }) {
  return (
    <SVGContainer style={{ overflow: 'visible' }}>
      <StrokePaths props={shape.props} color={inkVar(shape.props.emphasis)} />
    </SVGContainer>
  );
}

function StrokePaths({ props, color }: { props: InkStrokeProps; color: string }) {
  const strokes = props.strokes as Stroke[];
  const paths = useMemo(() => {
    return revealStrokes(strokes, props.progress).map((p) =>
      outlineToPath(getStroke(p.points, { ...STROKE_STYLE, size: props.size, last: p.complete })),
    );
  }, [strokes, props.progress, props.size]);
  const marker = props.role === 'highlight' || props.role === 'underline';
  return (
    <g
      fill={color}
      style={marker ? { mixBlendMode: 'multiply' } : undefined}
      opacity={marker ? 0.92 : 1}
    >
      {paths.map((d, i) => (
        // biome-ignore lint/suspicious/noArrayIndexKey: strokes are positional and never reorder
        <path key={i} d={d} />
      ))}
    </g>
  );
}
